### ISSUE TITLE
Towns/nations losing bank on /reload

### ISSUE THREAD

**Issue by cblair91** [ElgarL/Towny#149]
On /reload, the towns and nations all seem to lose their bank.

**Comment by mwkaicz** [comment]
Confirmed in v0.89.2.0, but not only on /reload ... few days it works good, but since last /reload it goes to the hell. Towns and nations lose all money instead of pay taxes. (Essentials just create new money accounts and lose previous data for each town/nation instead take taxes)

**Comment by mwkaicz** [comment]
Ok, I found source of this error. Few days ago server fell down and about 10 players lost money accounts. When Towny reached new day and tried to take money, It created new accouts for these players with default (Essentials) value, but (because some of these players were in towns) it made the same thing with all town_ and nation_ accounts.
Next day was again without any problems.

Can anyone confirm, if this is possible?

**Comment by TekkitCommando** [comment]
It is very possible
